apiVersion: tekton.dev/v1beta1
kind: Task
metadata:  
  name: hello-world
spec:
  steps:
    - name: hello
      image: gcr.io/cloud-builders/gcloud
      command: ["echo"]
      args: ["Hello, World!"]